---
title: "Instacart Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
  output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("instacart")
instacart_small = instacart |>
filter(!is.na(product_name), !is.na(department), !is.na(aisle)) |>
sample_n(5000) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot: Order Hour vs. Add to Cart Order

```{r}
scatter_data = instacart_small |>
  mutate(
  text_label = str_c(
  "Product: ", product_name,
  "Department: ", department,
  "Hour: ", order_hour_of_day)
  )

plot_ly(
  data = scatter_data,
  x = ~order_hour_of_day,
  y = ~add_to_cart_order,
  type = "scatter",
  mode = "markers",
  color = ~department,
  text = ~text_label,
  alpha = 0.5
  ) |>
  layout(
  title = "Add to Cart Order vs. Hour of Day",
  xaxis = list(title = "Hour of Day"),
  yaxis = list(title = "Add to Cart Order")
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot: Days Since Prior Order by Day of Week

```{r}
box_data = instacart_small |>
  filter(!is.na(days_since_prior_order)) |>
  mutate(
    order_dow = factor(order_dow, 
    labels = c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")))

plot_ly(
  data = box_data,
  x = ~order_dow,
  y = ~days_since_prior_order,
  color = ~order_dow,
  type = "box",
  colors = "viridis") |>
layout(
  title = "Days Since Prior Order by Day of Week",
  xaxis = list(title = "Day of Week"),
  yaxis = list(title = "Days Since Prior Order")
)

```

### Bar Chart: Most Common Departments

```{r}
bar_data = instacart_small |>
  count(department, sort = TRUE) |>
  mutate(department = fct_reorder(department, n))

plot_ly(
  data = bar_data,
  x = ~department,
  y = ~n,
  color = ~department,
  type = "bar",
  colors = "viridis") |>
  layout(
    title = "Most Common Departments in Sample",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Number of Products")
  )

```

