---
title: "Resume"
output: html_document
---

# Education

- **M.S. in Public Health Data Science**, Columbia Mailman, Expected May 2027
- **Bachelor's of Arts**, Biochemistry and Computer Science, Wellesley College, May 2023

# Professional Experience

####  Research Technician at the Reinherz Lab, Dana Farber Cancer Institute — *June 2023 - June 2025*

- Development of DNA constructs for various T-Cell Receptors (TCRs) via cloning, primarily using PCR
and golden gate cloning techniques.
- Experience with HEK293 cell culture for TCR expression.
- Responsible for TCR protein purification for structural analysis purposes using affinity and size
exclusion chromatography.
- Designed experiments for yield prediction from small scale protein purification.
- Independently designed and constructed mutants using protein structural (Pymol) and yield data
analysis to improve protein expression without compromising signaling and stability.
- Analysis of data, documentation, and presentation of results.

#### Software Engineering Intern , Merck, NJ — *May 2022 – September 2022*
- Worked on the addition of new and the honing of existing features of the web-tool ‘Assembler’ using React Native, which allows for a streamlined ability for doctors and public health agencies to market and share information about Merck’s available therapies to patients.

#### Research Assistant, SecureDNA, Massachusetts Institute of Technology Media Lab — *May 2021 – September 2021*

- Aided in the development of software responsible for the global prevention of the synthesis of biohazardous DNA fragments.
- Individual work included the parallelization of python code, preventing the accumulation of end to end DNA overlaps in hazardous DNA, and reducing time complexity of the Metropolis Hastings algorithm for the random sampling of DNA sequences.

# Skills

- Programming: Python (advanced), C++ (beginner), MATLAB (intermediate), React
Native (intermediate), Java (intermediate), JavaScript (intermediate), CSS (intermediate), R(in progress)
- Tools: Git, RStudio  



